camptocamp/bivac

README.md, conplicity.go
Requires https://github.com/fsouza/go-dockerclient/pull/504
=> Ignore volumes marked as io.conplicity.<vol>.ignore=true

conplicity.go
This needs refactoring to avoid duplicated code
=> [WIP] dump databases before backup

conplicity.go, handler/handler.go, handler/handler_test.go, providers/default.go, providers/mysql.go, providers/openldap.go, providers/postgresql.go, providers/provider.go, util/util.go, util/util_test.go, volume/volume.go, volume/volume_test.go
Port to github.com/docker/engine-api (fix #37) (fix #51)
=> Port to github.com/docker/engine-api

conplicity.go, handler/handler.go
Push early to keep track of backup progress
=> Add backupStartTime and backupEndTime metrics

volume/volume.go
Use interface{} in a smarter way to avoid
back and forth conversions.
Assume string kind if mismatch.
=> Avoid asserting config params as string

conplicity.go
Conplicity sometimes fails with
```
Failed to get exiting Prometheus metrics: failed to get existing metrics from Prometheus: Get http://pushgateway.metrics:9091/metrics: dial tcp 10.42.24.102:9091: getsockopt: no route to host
```
This is weird because the dns resolution works but not the routing...
If I restart the container it works.
Maybe some kind of race condition?
=> "Failed to get exiting Prometheus metrics"

conplicity.go, engines/duplicity.go, handler/handler.go, metrics/metrics.go, volume/volume.go
As per https://github.com/prometheus/pushgateway/issues/102
=> Use volume as a primary key in PushGateway

providers/provider.go, providers/provider_test.go
Mount the volume in a container to detect which provider to use.
Depends on #146.
=> Abstract provider detection

engines/restic.go
cf: https://github.com/restic/restic/issues/1690#issuecomment-377496565
=> restic engine: check if repository exists before init (#148)

engines/restic.go
If Restic fails to get the snapshots or to initialize a repository, the backup will silently fail. This PR is a quick fix designed to prevent this behavior without making a lot of changes.
=> Prevent backup from silently failing

engines/restic.go
Also checks that there is at least one snapshots
=> Check error from snapshots() function

orchestrators/docker.go
=> Don't allocate pseudo-tty for docker container

engines/restic.go
And send this date to pushgateway
Include lastBackup metrics in forget()
=> Check last backup date from bucket

cmd/restic/restic.go
=> Correctly named restic package

providers-config.default.toml
=> Add support for mongo backups

Makefile
=> Updated golint path

openshift/README.md, openshift/bivac-template.yaml, openshift/bivac2-agent.template.yaml
new template for bivac2-based manager deployment.
Needs fixing of #280 before cross-namespace backups will work.
=> openshift/bivac-template.yaml: template for bivac manager v2.0

pkg/orchestrators/kubernetes.go
=> Fixed container exec across namespace

cmd/manager/manager.go, pkg/orchestrators/kubernetes.go, pkg/volume/volume.go
=> Added kubernetes whitelist annotation support

cmd/manager/manager.go, internal/manager/manager.go
=> Added parallel count config

go.mod, go.sum
=> Updated go.mod and go.sum

.gitignore
=> Ignore bivac binary

Makefile
=> Improved clean script

cmd/manager/manager.go, internal/manager/manager.go, internal/manager/manager_test.go
This PR should fix the issue #295.
=> Allow setting a custom backup interval

pkg/orchestrators/kubernetes.go
This may contains network configuration for example
fix #386
=> feat: Filter annotations forwarded the agents
